image: maven:3.6.3-jdk-11

services:
  - postgres:13.1-alpine

variables:
  POSTGRES_DB: "workout_planning"
  POSTGRES_HOST_AUTH_METHOD: trust

  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true "

stages:
  - version
#  - compile
#  - test

view:
  stage: version
  script:
    - mvn -version
    - java -version
    - cat /proc/version
  tags:
    - jdk_11
#
#compile:
#  stage: compile
#  script:
#    - mvn $MAVEN_CLI_OPTS clean compile
#  tags:
#    - jdk_11
#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#  tags:
#    - jdk_11
