image: maven_mysql_jdk11:latest

services:
  - postgres:13.1-alpine

variables:
  POSTGRES_DB: "workout_planning"
  POSTGRES_HOST_AUTH_METHOD: trust

  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true "

stages:
#  - compile
  - test

#compile:
#  stage: compile
#  script:
#    - mvn -version
#    - java -version
#    - mvn $MAVEN_CLI_OPTS clean compile
#  tags:
#    - mysql
test:
  stage: test
  script:
    - yum install net-tools
    - netstat -ltpn
#    - mvn $MAVEN_CLI_OPTS test
  tags:
    - mysql
