image: maven:3.6.3-jdk-11

services:
  - postgres:14.3


variables:
  POSTGRES_DB: "workout_planning"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST_AUTH_METHOD: trust

  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true "

stages:
  - version
  - compile-test

view_version:
  stage: version
  script:
    - mvn -version
    - java -version
    - cat /proc/version
  tags:
    - jdk_11

compile-test:
  stage: test
  script:
    - service postgresql start
    - mvn $MAVEN_CLI_OPTS clean compile test
  tags:
    - jdk_11
