version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 2000:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: "workout_planning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    restart: always
    volumes:
      - ../../data/dump:/db-dump
    ports:
      - "5432:5432"
